name: Run Playwright tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Plawright dependencies
        run: npx playwright install-deps
        working-directory: ProtoRabbit-Electron

      - name: Install dependencies
        run: npm i
        working-directory: ProtoRabbit-Electron

      - name: Build ProtoRabbit
        run: npm run build
        working-directory: ProtoRabbit-Electron

      # - name: Archive out directory
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: out-dir
      #     path: ProtoRabbit-Electron/out/

      - name: Run Playwright tests
        run: xvfb-run --auto-servernum npx playwright test
        working-directory: ProtoRabbit-Electron
