name: Run Playwright tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm i
        working-directory: ProtoRabbit-Electron

      - name: Build ProtoRabbit
        run: npm run build
        working-directory: ProtoRabbit-Electron

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ProtoRabbit-Electron-dir
          path: ProtoRabbit-Electron/

      - name: Run Playwright tests
        run: DEBUG=pw:api npx playwright test
        working-directory: ProtoRabbit-Electron
