name: Run ProtoRabbit-MAUI Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    # necessary for setup-dotnet
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
    steps:
      - uses: actions/checkout@main

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Show DOTNET SDKs
        run: dotnet --list-sdks

      # - name: Restore Packages
      #   run: dotnet restore ProtoRabbit.sln

      # - name: Build solution
      #   run: dotnet build ProtoRabbit.sln --no-restore --configuration Release

      # - name: Run Tests
      #   run: dotnet test ProtoRabbit.sln --no-build --configuration Release
