name: Run ProtoRabbit-MAUI Tests
on:
  workflow_dispatch:
  push:
    paths:
      - "ProtoRabbit-MAUI/**"
jobs:
  ProtoRabbit-MAUI Tests:
    runs-on: ubuntu-latest
    # These permissions are necessary for 'publish-unit-test-result-action'
    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@main

      - name: Install tizen workload to make GitHub happy - necessary for some reason.
        run: dotnet workload restore ProtoRabbit-MAUI/ProtoRabbit-MAUI-Test/ProtoRabbit-MAUI-Test.csproj

      - name: Show DOTNET SDKs
        run: dotnet --list-sdks

      - name: Restore Packages
        run: dotnet restore ProtoRabbit-MAUI/ProtoRabbit-MAUI-Test/ProtoRabbit-MAUI-Test.csproj

      - name: Run Tests
        run: dotnet test --logger trx ProtoRabbit-MAUI/ProtoRabbit-MAUI-Test/ProtoRabbit-MAUI-Test.csproj

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.4.2
        with:
          files: |
            **/ProtoRabbit-MAUI-Test/**/*.trx
